# This file was generated by GoReleaser. DO NOT EDIT.
cask "safu" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "132da136b4669f06d0abb4e7700396d8b7c09920f895f9eba90fa51ab0d9f8bd"
      url "https://github.com/StackSatoshis/safu/releases/download/v0.1.1/safu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "47a50da59a5df1ff837479ecd7bb01af2c24e25ee2597227c880c5ab5cf28a27"
      url "https://github.com/StackSatoshis/safu/releases/download/v0.1.1/safu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "54cd8629cfed2b5d8c06ad88a5a11f71dc078e44bf586bee942e34c118e47478"
      url "https://github.com/StackSatoshis/safu/releases/download/v0.1.1/safu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "85af576343f3b95a02571fbf428512b77354f579d1c72b6efcbe7a2ca10624c5"
      url "https://github.com/StackSatoshis/safu/releases/download/v0.1.1/safu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "safu"
  desc "Safer, smarter shell — guards destructive commands, audits packages"
  homepage "https://safu.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "safu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/safu"],
                     print_stderr: false
    end
  end

  caveats <<~EOS
    safu only places the binary. To turn it on in your shell, run:
      safu setup            (interactive)
      safu init --write-rc  (non-interactive)
  EOS
end
