# This file was generated by GoReleaser. DO NOT EDIT.
cask "safu" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "e85a87a3a11ae050bcbe0e4b52414b549b7ae8f22c1070aad0f02ec15359116d"
      url "https://github.com/StackSatoshis/safu/releases/download/v0.1.0/safu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c4c2f81247e727d19a85102844f4b9704bead05c4192b8cf62d1323383db987"
      url "https://github.com/StackSatoshis/safu/releases/download/v0.1.0/safu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "581b6d78cbeaed8fd915adbb3509e69171c53116aa13eb1dbc47303085069d04"
      url "https://github.com/StackSatoshis/safu/releases/download/v0.1.0/safu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "711d8c6ba3ab12d641af18931963b2aa92a483053c8df7f31165779577bd30a4"
      url "https://github.com/StackSatoshis/safu/releases/download/v0.1.0/safu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "safu"
  desc "Safer, smarter shell — guards destructive commands, audits packages"
  homepage "https://safu.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "safu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/safu"],
                     print_stderr: false
    end
  end

  caveats <<~EOS
    safu only places the binary. To turn it on in your shell, run:
      safu setup            (interactive)
      safu init --write-rc  (non-interactive)
  EOS
end
